from __future__ import annotations

from enum import IntEnum

BASE_UUID = "-0000-1000-8000-0026BB765291"


def hap_uuid(short: int) -> str:
    return f"{short:08X}{BASE_UUID}"


CATEGORY_TARGET_CONTROLLER = 32


class Button(IntEnum):
    UNDEFINED = 0
    MENU = 1
    PLAY_PAUSE = 2
    TV_HOME = 3
    SELECT = 4
    ARROW_UP = 5
    ARROW_RIGHT = 6
    ARROW_DOWN = 7
    ARROW_LEFT = 8
    VOLUME_UP = 9
    VOLUME_DOWN = 10
    SIRI = 11
    POWER = 12
    GENERIC = 13


class ButtonState(IntEnum):
    UP = 0
    DOWN = 1


class TargetCategory(IntEnum):
    APPLE_TV = 0x18


class TargetOperation(IntEnum):
    UNDEFINED = 0
    LIST = 1
    ADD = 2
    REMOVE = 3
    RESET = 4
    UPDATE = 5


class HDSStatus(IntEnum):
    SUCCESS = 0
    OUT_OF_MEMORY = 1
    TIMEOUT = 2
    HEADER_ERROR = 3
    PAYLOAD_ERROR = 4
    MISSING_PROTOCOL = 5
    PROTOCOL_SPECIFIC_ERROR = 6


class HDSCloseReason(IntEnum):
    NORMAL = 0
    NOT_ALLOWED = 1
    BUSY = 2
    CANCELLED = 3
    UNSUPPORTED = 4
    UNEXPECTED_FAILURE = 5
    TIMEOUT = 6
    BAD_DATA = 7
    PROTOCOL_ERROR = 8
    INVALID_CONFIGURATION = 9


# Service UUIDs
SERVICE_TARGET_CONTROL_MANAGEMENT = hap_uuid(0x122)
SERVICE_TARGET_CONTROL = hap_uuid(0x125)
SERVICE_AUDIO_STREAM_MANAGEMENT = hap_uuid(0x127)
SERVICE_DATA_STREAM_TRANSPORT_MANAGEMENT = hap_uuid(0x129)
SERVICE_SIRI = hap_uuid(0x133)

# Characteristic UUIDs
CHAR_ACTIVE = hap_uuid(0xB0)
CHAR_ACTIVE_IDENTIFIER = hap_uuid(0xE7)
CHAR_BUTTON_EVENT = hap_uuid(0x126)
CHAR_TARGET_CONTROL_SUPPORTED_CONFIGURATION = hap_uuid(0x123)
CHAR_TARGET_CONTROL_LIST = hap_uuid(0x124)
CHAR_SUPPORTED_AUDIO_STREAM_CONFIGURATION = hap_uuid(0x115)
CHAR_SELECTED_AUDIO_STREAM_CONFIGURATION = hap_uuid(0x128)
CHAR_SUPPORTED_DATA_STREAM_TRANSPORT_CONFIGURATION = hap_uuid(0x130)
CHAR_SETUP_DATA_STREAM_TRANSPORT = hap_uuid(0x131)
CHAR_SIRI_INPUT_TYPE = hap_uuid(0x132)
CHAR_VERSION = hap_uuid(0x37)

# HAP Target Control TLV8
TC_MAXIMUM_TARGETS = 0x01
TC_TICKS_PER_SECOND = 0x02
TC_SUPPORTED_BUTTON_CONFIGURATION = 0x03
TC_TYPE = 0x04

SUPPORTED_BUTTON_ID = 0x01
SUPPORTED_BUTTON_TYPE = 0x02

TC_LIST_OPERATION = 0x01
TC_LIST_TARGET_CONFIGURATION = 0x02

TARGET_IDENTIFIER = 0x01
TARGET_NAME = 0x02
TARGET_CATEGORY = 0x03
TARGET_BUTTON_CONFIGURATION = 0x04

BUTTON_CONFIGURATION_ID = 0x01
BUTTON_CONFIGURATION_TYPE = 0x02
BUTTON_CONFIGURATION_NAME = 0x03

BUTTON_EVENT_ID = 0x01
BUTTON_EVENT_STATE = 0x02
BUTTON_EVENT_TIMESTAMP = 0x03
BUTTON_EVENT_ACTIVE_IDENTIFIER = 0x04

# Audio configuration TLV8
AUDIO_STREAM_CONFIGURATION = 0x01
AUDIO_CODEC_TYPE = 0x01
AUDIO_CODEC_PARAMETERS = 0x02
AUDIO_CHANNELS = 0x01
AUDIO_BITRATE = 0x02
AUDIO_SAMPLE_RATE = 0x03
AUDIO_PACKET_TIME = 0x04
AUDIO_CODEC_OPUS = 0x03
AUDIO_BITRATE_VARIABLE = 0x00
AUDIO_SAMPLE_RATE_16_KHZ = 0x01

# HDS setup TLV8
HDS_TRANSFER_TRANSPORT_CONFIGURATION = 0x01
HDS_TRANSPORT_TYPE = 0x01
HDS_HOMEKIT_DATA_STREAM = 0x00
HDS_SESSION_COMMAND_TYPE = 0x01
HDS_SESSION_TRANSPORT_TYPE = 0x02
HDS_CONTROLLER_KEY_SALT = 0x03
HDS_START_SESSION = 0x00
HDS_SETUP_STATUS = 0x01
HDS_SETUP_SESSION_PARAMETERS = 0x02
HDS_ACCESSORY_KEY_SALT = 0x03
HDS_TCP_LISTENING_PORT = 0x01

HDS_PROTOCOL_CONTROL = "control"
HDS_PROTOCOL_TARGET_CONTROL = "targetControl"
HDS_PROTOCOL_DATA_SEND = "dataSend"
HDS_TOPIC_HELLO = "hello"
HDS_TOPIC_WHOAMI = "whoami"
HDS_TOPIC_OPEN = "open"
HDS_TOPIC_DATA = "data"
HDS_TOPIC_ACK = "ack"
HDS_TOPIC_CLOSE = "close"
